import react from "react";

export const Glossary=()=>{
    return(
        <div className="container py-5">
            <div className="text-center goldTitle"> <h1>Glossary</h1></div>
            <h3 className="goldTitle">Action</h3>
            <p className="text-white">This is the number of people who bet on both sides, games or sporting events.</p>
            <h3 className="goldTitle">Against the Spread ATS</h3>
            <p className="text-white">The Against the Spread or ATS is when you bet on the opposite side of a point spread.</p>
            <h3 className="goldTitle">Bad Beat</h3>
            <p className="text-white">A period of time with more losing wagers than winning ones.</p>
            <h3 className="goldTitle">Beard</h3>
            <p className="text-white">People who want to remain anonymous and not have their bets revealed often use this strategy. They are typically sharp people with good intuition, which helps them succeed in the betting world.</p>
            <h3 className="goldTitle">Book</h3>
            <p className="text-white">The word “book” is short for "sportsbook," which are establishments who take bets on sporting events.</p>
            <h3 className="goldTitle">Bookmaker</h3>
            <p className="text-white">This individual or group take bets of any sporting event. They are always ready to take your bet and have a great sense for what will happen next.</p>
            <h3 className="goldTitle">Buy Points</h3>
            <p className="text-white">This method allows bettors move point spreads in their favor by paying a small fee that will increase your chances of winning even more.</p>
            <h3 className="goldTitle">Chalk</h3>
            <p className="text-white">This term refers to the team that's expected, or most likely going into an event.</p>
            <h3 className="goldTitle">Circled Game</h3>
            <p className="text-white">In a circled game, there are lower limits due to various factors.</p>
            <h3 className="goldTitle">Cover</h3>
            <p className="text-white">When a side wins against the spread, it’s called covering. If they fall within margin and beat point spreads then that's called winning.</p>
            <h3 className="goldTitle">Dime</h3>
            <p className="text-white">A bet for $1000.</p>
            <h3 className="goldTitle">Dime Line</h3>
            <p className="text-white">The “juice” or vig on a betting line can be as high at 10%.</p>
            <h3 className="goldTitle">Dog</h3>
            <p className="text-white">The term “underdog” refers to teams that are expected to lose.</p>
            <h3 className="goldTitle">Edge</h3>
            <p className="text-white">The advantage of the house on any specific event/game.</p>
            <h3 className="goldTitle">Even Money</h3>
            <p className="text-white">This means that, when you win, you will be paid an amount equal to your bet.</p>
            <h3 className="goldTitle">Favorite</h3>
            <p className="text-white">The team or individual expected to win.</p>
            <h3 className="goldTitle">Futures</h3>
            <p className="text-white">The process of researching, analyzing and predicting a sports betting event.</p>
            <h3 className="goldTitle">Hedging</h3>
            <p className="text-white">Reduce or mitigate your risk with another wager.</p>
            <h3 className="goldTitle">Hook</h3>
            <p className="text-white">Half-point.</p>
            <h3 className="goldTitle">Juice</h3>
            <p className="text-white">The sportsbook's commission is determined by the type of bet that they are on.</p>
            <h3 className="goldTitle">Laying the Points</h3>
            <p className="text-white">When betting on the favorite and making a wager for them as well.</p>
            <h3 className="goldTitle">Limit</h3>
            <p className="text-white">The amount you can bet on any given event varies from book to book.</p>
            <h3 className="goldTitle">Lines</h3>
            <p className="text-white">Betting odds are a synonym for the point spread, moneyline or totals.</p>
            <h3 className="goldTitle">Linemaker</h3>
            <p className="text-white">The bookmaker who sets the betting line and then manages it as action comes in.</p>
            <h3 className="goldTitle">Listed Pitchers</h3>
            <p className="text-white">Listing a pitcher means you must put them on the field for your bet to count. If they don't start, then it's void and won’t pay out.</p>
            <h3 className="goldTitle">Lock</h3>
            <p className="text-white">The favorite in this race is expected to win with ease.</p>
            <h3 className="goldTitle">Longshot</h3>
            <p className="text-white">Longshots are teams or sides that many people don't consider to have a chance at winning.</p>
            <h3 className="goldTitle">Moneyline</h3>
            <p className="text-white">This type of bet is usually only offered at sporting events and focuses on who will win an even.</p>
            <h3 className="goldTitle">Nickel</h3>
            <p className="text-white">A $500 wager on any sport.</p>
            <h3 className="goldTitle">Nickel Line</h3>
            <p className="text-white">A betting line in which the “juice” or “vig” is five percent.</p>
            <h3 className="goldTitle">No Action</h3>
            <p className="text-white">This is when a bet is cancelled, and the stake is returned to the betto.</p>
            <h3 className="goldTitle">Off the Board</h3>
            <p className="text-white">When a game becomes off the board, it can no longer be bet on due to certain circumstances.</p>
            <h3 className="goldTitle">Over</h3>
            <p className="text-white">This is the point at which the consolidated all out score of the different sides goes over the set absolute for the game.</p>
            <h3 className="goldTitle">Over/Under</h3>
            <p className="text-white">A number set by the oddsmakers that extends the joined last score of the two sides. The bettor can then pick whether a game will go over or under that number.</p>
            <h3 className="goldTitle">Parlay</h3>
            <p className="text-white">A kind of bet where different choices are chosen. Every one of those choices should win for the parlay to win. The payout is greater in a parlay, despite the fact that the danger is more prominent also</p>
            <h3 className="goldTitle">Pay Per Head/Price Per Head</h3>
            <p className="text-white">Is an onshore bookmaker providing their sports betting services to a specific betting cliental with the help of a post-up offshore online.</p>
            <h3 className="goldTitle">Pick’em</h3>
            <p className="text-white">In a game where the point spread represents equality, it makes no difference whether one side is favorite or underdog.</p>
            <h3 className="goldTitle">Point Spread</h3>
            <p className="text-white">A point spread is a handicap that makes the outcome of an event less predictable by having one team win or lose more than their opponent. Points are given or taken in order to set a balance between the two.</p>
            <h3 className="goldTitle">Puckline</h3>
            <p className="text-white">This is a point spread in hockey that is set all the time at 1.5 goals.</p>
            <h3 className="goldTitle">Prop Bet</h3>
            <p className="text-white">A type of bet that focuses on various other activities, stats or happenings during an event instead solely focusing on who is winning. For example, total rushing yards by a player with points scored in the NBA game and if there's going to be an interception thrown within this timeframe too.</p>
            <h3 className="goldTitle">Push</h3>
            <p className="text-white">This is a tie, and the stake is gotten back to the bettor.</p>
            <h3 className="goldTitle">Runline</h3>
            <p className="text-white">A point spread of - 1.5 or +1.5 in a baseball game. This implies you can either wager a group to win by 1.5, or you can get a group with 1.5 runs.</p>
            <h3 className="goldTitle">Sharp</h3>
            <p className="text-white">A professional or smart bettor who is well-researched and well-informed.</p>
            <h3 className="goldTitle">Side</h3>
            <p className="text-white">Another word for spread.</p>
            <h3 className="goldTitle">Spread</h3>
            <p className="text-white">Short form for the term “point spread.”</p>
            <h3 className="goldTitle">Straight Bet</h3>
            <p className="text-white">Simply an essential bet in one group or side.</p>
            <h3 className="goldTitle">Square</h3>
            <p className="text-white">An unpracticed, uninformed bettor.</p>
            <h3 className="goldTitle">Steam</h3>
            <p className="text-white">A quick change in the wagering line, for the most part in view of sharp activity.</p>
            <h3 className="goldTitle">Taking the Points</h3>
            <p className="text-white">Betting on a positive spread.</p>
            <h3 className="goldTitle">Teaser</h3>
            <p className="text-white">In this game, you are allowed to move the points in your favor. In return for doing so, getting lower payouts than normal.</p>
            <h3 className="goldTitle">Total</h3>
            <p className="text-white">The joined last score of the game.</p>
            <h3 className="goldTitle">Under</h3>
            <p className="text-white">The total points scored either by one or both teams stayed below the expected total given by the bookmaker.</p>
            <h3 className="goldTitle">Underdog</h3>
            <p className="text-white">The team that is not expected to win.</p>
            <h3 className="goldTitle">Vigorish</h3>
            <p className="text-white">This is an equivalent word for juice, which is the commission the sportsbook takes.</p>
            <h3 className="goldTitle">Wiseguy</h3>
            <p className="text-white">One more term to depict a "sharp" or "savvy" bettor. In many cases, this is an expert who is very much educated and learne.</p>
        </div>
    )
}